import { ITEM_BY_NAME, ITEM_CATALOG } from "./item-weights";

export interface WeaponCapture { weapon: string; weaponItem: "arma baixo calibre" | "arma medio calibre" | "arma alto calibre"; ammo: number; ammoItem: "balas baixo" | "balas medio" | "balas alto"; accessoryCount: number; }
export interface ItemMatch { item: string; qty: number; kg: number; unitKg: number | null; confidence: number; confidenceLevel: "high" | "medium" | "low"; matchReason: string; }
export interface ParseResult { text: string; weights: ItemMatch[]; weaponCapture: WeaponCapture | null; overallConfidence: number; }
type Hint = { item: string; pos: number; unitKg: number }; type Pair = { qty: number; kg: number; pos: number };
function normalize(text:string){return text.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9().:\n\s-]/g," ").replace(/\s+/g," ").trim();}
function fixOcrTypos(text:string){let s=text;const rules:[RegExp,string][]=[[/\bLOCKPECK\b/gi,"LOCKPICK"],[/\bLOCKPICK\s+AVANCAD[AO]\b/gi,"LOCKPICK AVANCADA"],[/\bTELEN[OÓ]VEL\b/gi,"TELEMOVEL"],[/\bTELEHOVEL\b/gi,"TELEMOVEL"],[/\bMOMOSHU\b/gi,"MONOSHU"],[/\bMEOWCHI\s+MOCHI\b/gi,"MEDWCHI MOCHI"],[/\bBTFANA\b/gi,"BIFANA"],[/\bCORRENTE\s+DE\s+DURO\b/gi,"CORRENTE DE OURO"],[/\b1BK\b/gi,"10K"],[/\b1OK\b/gi,"10K"],[/\bREPARA[CÇ]AD\b/gi,"REPARACAO"],[/\bSUMO\s+HARACUJA\b/gi,"SUMO MARACUJA"],[/\bSUHO\s+MARACUJA\b/gi,"SUMO MARACUJA"]];for(const[r,x]of rules)s=s.replace(r,x);return s;}
function extractPairs(text:string):Pair[]{const out:Pair[]=[];const re=/(\d{1,6})\s*\(\s*(\d+(?:\.\d+)?)\s*\)/g;let m:RegExpExecArray|null;while((m=re.exec(text))){const qty=Number(m[1]),kg=Number(m[2]);if(Number.isFinite(qty)&&Number.isFinite(kg)&&qty>0&&kg>=0)out.push({qty,kg,pos:m.index});}return out;}
const HINTS:Array<[RegExp,string]>=[[/compact\s+rifle/i,"arma alto calibre"],[/carregador\s+de\s+rifle/i,"carregador alto calibre"],[/carregador\s+de\b/i,"carregador alto calibre"],[/restos\s+eletronicos/i,"eletronicos"],[/restos\b/i,"eletronicos"],[/eletronicos/i,"eletronicos"],[/machine\s+pistol/i,"arma medio calibre"],[/assault\s+smg/i,"arma medio calibre"],[/corrente\s+de\s+ouro\s+10k/i,"corrente 10k"],[/corrente\s+de\s+ouro/i,"corrente"],[/anel\s+de\s+diamante/i,"anel"],[/ouro\s+estatal/i,"ouro estatal"],[/sumo\s+ananas/i,"sumo ananas"],[/sumo\s+laranja/i,"sumo laranja"],[/sumo\s+maracuja/i,"sumo maracuja"],[/bifana/i,"bifana"],[/candy\s+cane/i,"candy cane"],[/radio/i,"radio"],[/telemovel/i,"telemovel"],[/petrol\s+can/i,"petrol can"],[/bandagem/i,"bandagem"],[/kit\s+reparacao/i,"kit reparacao"],[/lockpick\s+avancada/i,"lockpick avancada"],[/lockpick/i,"lockpick"],[/dinheiro/i,"dinheiro"],[/quadro/i,"quadro"],[/arma\s+alto\s+calibre/i,"arma alto calibre"],[/arma\s+medio\s+calibre/i,"arma medio calibre"],[/arma\s+baixo\s+calibre/i,"arma baixo calibre"]];
const EXTRA_WEIGHTS:Record<string,number>={"candy cane":.2};
function unitWeight(i:string){return EXTRA_WEIGHTS[i]??ITEM_BY_NAME.get(i)?.unitKg??null;}
function displayName(i:string){const d=ITEM_BY_NAME.get(i);if(d)return d.displayName;if(i==="candy cane")return "Candy Cane";if(i==="eletronicos")return "Restos Eletrónicos";return i.replace(/\b\w/g,c=>c.toUpperCase());}
function collectHints(text:string):Hint[]{const out:Hint[]=[];for(const[re,item]of HINTS){const rx=new RegExp(re.source,`${re.flags.replace(/g/g,"")}g`);let m:RegExpExecArray|null;while((m=rx.exec(text))){const u=unitWeight(item);if(u!=null)out.push({item,pos:m.index,unitKg:u});}}out.sort((a,b)=>a.pos-b.pos||b.item.length-a.item.length);const d:Hint[]=[];for(const h of out){const p=d[d.length-1];if(p&&Math.abs(p.pos-h.pos)<4)continue;d.push(h);}return d;}
function weightClose(a:number,b:number){return b>0&&(Math.abs(a-b)/b<=.12||Math.abs(a-b)<=.02);}
function confidence(a:number,b:number|null,n:boolean){if(b==null||b<=0)return n?.75:.5;const d=Math.abs(a-b)/b;return d<=.05?(n?.95:.85):d<=.12?(n?.7:.55):(n?.4:.2);}
function level(c:number){return c>=.8?"high":c>=.55?"medium":"low" as const;}
function matchPairsToHints(pairs:Pair[],hints:Hint[]):ItemMatch[]{const results:ItemMatch[]=[];const used=new Set<number>();let last=-1;for(const p of pairs){const u=p.kg/p.qty;let best=-1;for(let i=last+1;i<hints.length;i++){if(used.has(i)||!weightClose(u,hints[i].unitKg))continue;best=i;break;}if(best<0){for(let i=0;i<hints.length;i++){if(!used.has(i)&&weightClose(u,hints[i].unitKg)){best=i;break;}}}if(best>=0){used.add(best);last=Math.max(last,best);const h=hints[best];const c=confidence(u,h.unitKg,true);results.push({item:h.item,qty:p.qty,kg:p.kg,unitKg:h.unitKg,confidence:c,confidenceLevel:level(c),matchReason:`Peso perfeito: ${p.kg} kg = ${p.qty} × ${h.unitKg} kg`});}else{const def=ITEM_CATALOG.find(x=>weightClose(u,x.unitKg));if(def){const c=confidence(u,def.unitKg,false);results.push({item:def.name,qty:p.qty,kg:p.kg,unitKg:def.unitKg,confidence:c,confidenceLevel:level(c),matchReason:`Peso reconhecido: ${p.kg} kg = ${p.qty} × ${def.unitKg} kg`});}}}return results;}
function detectWeaponCapture(text:string):WeaponCapture|null{const weapon=text.match(/(?:ARMA|WEAPON)\s*:\s*([^\n]+)/i)?.[1]?.trim()||"";const ammo=Number(text.match(/MUNI[CÇ][AÃ]O\s*:\s*(\d+)/i)?.[1]||0);if(!weapon&&!ammo)return null;let weaponItem:WeaponCapture["weaponItem"]="arma baixo calibre";if(/ALTO|COMBAT PDW|RIFLE|CARABIN|SNIPER|MACHINE PISTOL/i.test(weapon))weaponItem="arma alto calibre";else if(/MEDIO|M[EÉ]DIO|SMG|PISTOL/i.test(weapon))weaponItem="arma medio calibre";const ammoItem=weaponItem==="arma alto calibre"?"balas alto":weaponItem==="arma medio calibre"?"balas medio":"balas baixo";const accessoryCount=Number(text.match(/ACESS[OÓ]RIOS?\s*:\s*(\d+)/i)?.[1]||0);return{weapon,weaponItem,ammo,ammoItem,accessoryCount};}
export function parseInventoryOCR(rawText:string):ParseResult{const fixed=fixOcrTypos(rawText),normalized=normalize(fixed),pairs=extractPairs(fixed),hints=collectHints(normalized),weights=matchPairsToHints(pairs,hints),text=weights.map(w=>`${w.qty} ${displayName(w.item)}`).join(", "),overallConfidence=weights.length?weights.reduce((s,w)=>s+w.confidence,0)/weights.length:0;return{text,weights,weaponCapture:detectWeaponCapture(fixed),overallConfidence};}
export function parseOcrText(rawText:string){return parseInventoryOCR(rawText).weights;}
